### ISSUE TITLE
In the web app run command, `-p` flag has some issues

### ISSUE THREAD

**Issue by weiseng18** [lunaflight/courserekt#17]
**Describe the bug**

`python -m src.web.main -p 5001` gives the following error:

`TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'`

If you go to `/src/web/main.py` and print `args.port`, you'll see that it is an array containing a single number.

**To Reproduce**

Run `python -m src.web.main -p 5001` at project root

**Expected behavior**

App runs at `localhost:5001`

**Comment by lunaflight** [comment]
UHHHH gg if true

**Comment by weiseng18** [comment]
(I think fix is simple, replace `args.port` with `args.port[0]` in `/src/web/main.py`

**Comment by lunaflight** [comment]
It would probably be more sound for the argument parser to accept exactly 1 argument, if possible, but I have not looked into this, so it would be parsed as a single item instead of putting it in an array
