### ISSUE TITLE
[Brave] Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by SpookyYomo** [lunaflight/courserekt#41]
## Platform
Browser: Brave Browser v1.69.153 on Windows 10 22H2
Browser: Brave Browser v1.68.134 on ArchLinux
On vercel, not local build.
## Developer Tools Warning/Error (Ctrl+Shift+I/F12)

This error is not pertaining to this bug report but is visible in the same context.
- 1 Error:
<details>
<summary>Debugger Message</summary>
```
Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
    jQueryDetection util.js:179
    <anonymous> util.js:195
    <anonymous> bootstrap.min.js:6
    <anonymous> bootstrap.min.js:6
util.js:179:13
```
The above is also present in Firefox, but is instead present in `util.js:179:12`

</details>

- 4 page errors:
<details open>
<summary>Debugger Message</summary>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.  

**Affected Resources**:

> Violating Node: `<label for ="year">...</label> == $0`  
> Violating Node: `<label for ="semester">...</label> == $0`  
> Violating Node: `<label for ="type">...</label> == $0`  
> Violating Node: `<label for ="course_codes">...</label> == $0`  

[Learn more: The label elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)
</details>
These are not present in Firefox.

Dug up into this issue _being unable to click into 24/25 on the browser_; similar issue to my attempt to split the pages out and testing on Firefox.

**Comment by lunaflight** [comment]
It seems like we can delete these wrongly used labels safely.
